import csv
import datetime
import os
import urllib
import xml.etree.ElementTree as ET

def current():
    """
    Return a dictionary of current index prices.
    """
    tree = ET.parse(urllib.urlopen("http://www.electusmatari.com/gmi/?format=xml"))
    result = {}
    for row in tree.findall("type"):
        result[row.attrib["name"]] = IndexRow(row)
    return result
         
class IndexRow(float):
    def __new__(cls, row):
        obj = super(IndexRow, cls).__new__(cls, row.attrib["republic"])
        for name, value in row.attrib.items():
            if name in ['name']:
                setattr(obj, name, value)
            elif "volume" in name:
                setattr(obj, name, long(value))
            elif value in ['None', None]:
                setattr(obj, name, 0)
            else:
                setattr(obj, name, float(value))
        return obj

GMI_CURRENT = "/home/forcer/public_html/eve/gmi/current.txt"
GMI_TIME = "/home/forcer/public_html/eve/gmi/gmi-%Y-%m-%d.txt"
PRICES_TIME = "/home/forcer/public_html/eve/grdprices/grd-pricelist-%Y-%m-%d.txt"
PRICES_CURRENT = "/home/forcer/public_html/eve/grd-pricelist.txt"

class HistoricIndex(object):
    def __init__(self):
        self.filecache = {}

    def get(self, typename, date=None):
        if date is None:
            date = datetime.datetime.utcnow()
        gmi = self.getgmi(date)
        if typename in gmi:
            return gmi[typename]
        prices = self.getprices(date)
        if typename in prices:
            return prices[typename]
        gmi = self.getgmi()
        if typename in gmi:
            return gmi[typename]
        prices = self.getprices()
        if typename in prices:
            return prices[typename]
        raise RuntimeError("Can't find index for %s" % typename)

    def getgmi(self, date=None):
        if date is None:
            return self.getfile(GMI_CURRENT)
        else:
            return self.getfile(date.strftime(GMI_TIME))

    def getprices(self, date=None):
        if date is None:
            return self.getfile(PRICES_CURRENT)
        else:
            return self.getfile(date.strftime(PRICES_TIME))

    def getfile(self, filename):
        if filename in self.filecache:
            return self.filecache[filename]
        if os.path.exists(filename):
            data = dict((row[0], float(row[1]))
                        for row in csv.reader(file(filename))
                        if row[1] not in ("", "Index"))
            self.filecache[filename] = data
            return data
        else:
            return {}



##################################################################
##################################################################
##################################################################

LOCALDIR = "/home/forcer/public_html/eve/gmi/"

TYPE_DATA = [
    # T1
    ("Minerals", ""),
    ("Tritanium", None),
    ("Pyerite", None),
    ("Mexallon", None),
    ("Isogen", None),
    ("Nocxium", None),
    ("Zydrine", None),
    ("Megacyte", None),
    ("Morphite", None),
    ("", ""),
    # Rigs
    ("Salvage Materials", ""),
    ("Alloyed Tritanium Bar", None),
    ("Armor Plates", None),
    ("Broken Drone Transceiver", None),
    ("Burned Logic Circuit", None),
    ("Charred Micro Circuit", None),
    ("Conductive Polymer", None),
    ("Contaminated Lorentz Fluid", None),
    ("Contaminated Nanite Compound", None),
    ("Damaged Artificial Neural Network", None),
    ("Defective Current Pump", None),
    ("Fried Interface Circuit", None),
    ("Malfunctioning Shield Emitter", None),
    ("Melted Capacitor Console", None),
    ("Scorched Telemetry Processor", None),
    ("Smashed Trigger Unit", None),
    ("Tangled Power Conduit", None),
    ("Thruster Console", None),
    ("Tripped Power Circuit", None),
    ("Ward Console", None),
    ("", ""),
    ("Tech 2 Salvage Materials", ""),
    ("Artificial Neural Network", None),
    ("Capacitor Console", None),
    ("Conductive Thermoplastic", None),
    ("Current Pump", None),
    ("Drone Transceiver", None),
    ("Enhanced Ward Console", None),
    ("Impetus Console", None),
    ("Intact Armor Plates", None),
    ("Intact Shield Emitter", None),
    ("Interface Circuit", None),
    ("Logic Circuit", None),
    ("Lorentz Fluid", None),
    ("Micro Circuit", None),
    ("Nanite Compound", None),
    ("Power Circuit", None),
    ("Power Conduit", None),
    ("Single-crystal Superalloy I-beam", None),
    ("Telemetry Processor", None),
    ("Trigger Unit", None),
    ("", ""),
    # POS stuff
    ("Ice Products", ""),
    ("Helium Isotopes", None),
    ("Hydrogen Isotopes", None),
    ("Nitrogen Isotopes", None),
    ("Oxygen Isotopes", None),
    ("Heavy Water", None),
    ("Liquid Ozone", None),
    ("Strontium Clathrates", None),
    ("", ""),
    ("Starbase Fuel", ""),
    ("Coolant", None),
    ("Enriched Uranium", None),
    ("Mechanical Parts", None),
    ("Oxygen", None),
    ("Robotics", None),
    ("", ""),
    # T2
    ("Datacores", ""),
    ("Datacore - Amarrian Starship Engineering", None),
    ("Datacore - Caldari Starship Engineering", None),
    ("Datacore - Electromagnetic Physics", None),
    ("Datacore - Electronic Engineering", None),
    ("Datacore - Gallentean Starship Engineering", None),
    ("Datacore - Graviton Physics", None),
    ("Datacore - High Energy Physics", None),
    ("Datacore - Hydromagnetic Physics", None),
    ("Datacore - Laser Physics", None),
    ("Datacore - Mechanical Engineering", None),
    ("Datacore - Minmatar Starship Engineering", None),
    ("Datacore - Molecular Engineering", None),
    ("Datacore - Nanite Engineering", None),
    ("Datacore - Nuclear Physics", None),
    ("Datacore - Plasma Physics", None),
    ("Datacore - Quantum Physics", None),
    ("Datacore - Rocket Science", None),
    ("", ""),
    ("Decryptors", ""),
    ("Advanced Theories", None),
    ("Assembly Instructions", None),
    ("Calibration Data", None),
    ("Circuitry Schematics", None),
    ("Circular Logic", None),
    ("Classic Doctrine", None),
    ("Collision Measurements", None),
    ("Engagement Plan", None),
    ("Formation Layout", None),
    ("Installation Guide", None),
    ("Interface Alignment Chart", None),
    ("Operation Handbook", None),
    ("Prototype Diagram", None),
    ("Sacred Manifesto", None),
    ("Stolen Formulas", None),
    ("Symbiotic Figures", None),
    ("Test Reports", None),
    ("Tuning Instructions", None),
    ("User Manual", None),
    ("War Strategon", None),
    ("", ""),
    ("Raw Moon Materials", ""),
    ("Atmospheric Gases", None),
    ("Cadmium", None),
    ("Caesium", None),
    ("Chromium", None),
    ("Cobalt", None),
    ("Dysprosium", None),
    ("Evaporite Deposits", None),
    ("Hafnium", None),
    ("Hydrocarbons", None),
    ("Mercury", None),
    ("Neodymium", None),
    ("Platinum", None),
    ("Promethium", None),
    ("Scandium", None),
    ("Silicates", None),
    ("Technetium", None),
    ("Thulium", None),
    ("Titanium", None),
    ("Tungsten", None),
    ("Vanadium", None),
    ("", ""),
    ("Processed Moon Materials", ""),
    ("Caesarium Cadmide", None),
    ("Carbon Polymers", None),
    ("Ceramic Powder", None),
    ("Crystallite Alloy", None),
    ("Dysporite", None),
    ("Fernite Alloy", None),
    ("Ferrofluid", None),
    ("Fluxed Condensates", None),
    ("Hexite", None),
    ("Hyperflurite", None),
    ("Neo Mercurite", None),
    ("Platinum Technite", None),
    ("Prometium", None),
    ("Rolled Tungsten Alloy", None),
    ("Silicon Diborite", None),
    ("Solerium", None),
    ("Sulfuric Acid", None),
    ("Titanium Chromide", None),
    ("Vanadium Hafnite", None),
    ("", ""),
    ("Advanced Moon Materials", ""),
    ("Crystalline Carbonide", None),
    ("Fermionic Condensates", None),
    ("Fernite Carbide", None),
    ("Ferrogel", None),
    ("Fullerides", None),
    ("Hypersynaptic Fibers", None),
    ("Nanotransistors", None),
    ("Phenolic Composites", None),
    ("Sylramic Fibers", None),
    ("Titanium Carbide", None),
    ("Tungsten Carbide", None),
    ("", ""),
    ("Tech 2 Construction Components", ""),
    ("Antimatter Reactor Unit", None),
    ("Crystalline Carbonide Armor Plate", None),
    ("Deflection Shield Emitter", None),
    ("Electrolytic Capacitor Unit", None),
    ("Emp Pulse Generator", None),
    ("Fernite Carbide Composite Armor Plate", None),
    ("Fusion Reactor Unit", None),
    ("Fusion Thruster", None),
    ("Gravimetric Sensor Cluster", None),
    ("Graviton Pulse Generator", None),
    ("Graviton Reactor Unit", None),
    ("Ion Thruster", None),
    ("Ladar Sensor Cluster", None),
    ("Laser Focusing Crystals", None),
    ("Linear Shield Emitter", None),
    ("Magnetometric Sensor Cluster", None),
    ("Magpulse Thruster", None),
    ("Nanoelectrical Microprocessor", None),
    ("Nanomechanical Microprocessor", None),
    ("Nuclear Pulse Generator", None),
    ("Nuclear Reactor Unit", None),
    ("Oscillator Capacitor Unit", None),
    ("Particle Accelerator Unit", None),
    ("Photon Microprocessor", None),
    ("Plasma Pulse Generator", None),
    ("Plasma Thruster", None),
    ("Pulse Shield Emitter", None),
    ("Quantum Microprocessor", None),
    ("Radar Sensor Cluster", None),
    ("Scalar Capacitor Unit", None),
    ("Superconductor Rails", None),
    ("Sustained Shield Emitter", None),
    ("Tesseract Capacitor Unit", None),
    ("Thermonuclear Trigger Unit", None),
    ("Titanium Diborite Armor Plate", None),
    ("Tungsten Carbide Armor Plate", None),
    ("", ""),
    ("Tech 2 Production", ""),
    ("Construction Blocks", None),
    ("Electronic Parts", None),
    ("Guidance Systems", None),
    ("Hydrogen Batteries", None),
    ("Miniature Electronics", None),
    ("Rocket Fuel", None),
    ("Superconductors", None),
    ("Transmitter", None),
    ("", ""),
    # T3
    ("Ancient Salvaged Materials", ""),
    ("Cartesian Temporal Coordinator", None),
    ("Central System Controller", None),
    ("Defensive Control Node", None),
    ("Electromechanical Hull Sheeting", None),
    ("Emergent Combat Analyzer", None),
    ("Emergent Combat Intelligence", None),
    ("Fused Nanomechanical Engines", None),
    ("Heuristic Selfassemblers", None),
    ("Jump Drive Control Nexus", None),
    ("Melted Nanoribbons", None),
    ("Modified Fluid Router", None),
    ("Neurovisual Input Matrix", None),
    ("Powdered C-540 Graphite", None),
    ("Resonance Calibration Matrix", None),
    ("Thermoelectric Catalysts", None),
    ("", ""),
    ("Ancient Relics", ""),
    ("Intact Armor Nanobot", None),
    ("Intact Electromechanical Component", None),
    ("Intact Hull Section", None),
    ("Intact Power Cores", None),
    ("Intact Thruster Sections", None),
    ("Intact Weapon Subroutines", None),
    ("Malfunctioning Armor Nanobot", None),
    ("Malfunctioning Electromechanical Component", None),
    ("Malfunctioning Hull Section", None),
    ("Malfunctioning Power Cores", None),
    ("Malfunctioning Thruster Sections", None),
    ("Malfunctioning Weapon Subroutines", None),
    ("Wrecked Armor Nanobot", None),
    ("Wrecked Electromechanical Component", None),
    ("Wrecked Hull Section", None),
    ("Wrecked Power Cores", None),
    ("Wrecked Thruster Sections", None),
    ("Wrecked Weapon Subroutines", None),
    ("", ""),
    ("Hybrid Datacores", ""),
    ("Datacore - Defensive Subsystems Engineering", None),
    ("Datacore - Electronic Subsystems Engineering", None),
    ("Datacore - Engineering Subsystems Engineering", None),
    ("Datacore - Offensive Subsystems Engineering", None),
    ("Datacore - Propulsion Subsystems Engineering", None),
    ("", ""),
    ("Hybrid Decryptors", ""),
    ("R.A.M.- Hybrid Technology", None),
    ("Amarr Hybrid Tech Decryptor", None),
    ("Caldari Hybrid Tech Decryptor", None),
    ("Gallente Hybrid Tech Decryptor", None),
    ("Minmatar Hybrid Tech Decryptor", None),
    ("", ""),
    ("Fullerenes", ""),
    ("Fullerite-C28", None),
    ("Fullerite-C32", None),
    ("Fullerite-C50", None),
    ("Fullerite-C60", None),
    ("Fullerite-C70", None),
    ("Fullerite-C72", None),
    ("Fullerite-C84", None),
    ("Fullerite-C320", None),
    ("Fullerite-C540", None),
    ("", ""),
    ("Hybrid Polymers", ""),
    ("C3-FTM Acid", None),
    ("Carbon-86 Epoxy Resin", None),
    ("Fullerene Intercalated Graphite", None),
    ("Fulleroferrocene", None),
    ("Graphene Nanoribbons", None),
    ("Lanthanum Metallofullerene", None),
    ("Methanofullerene", None),
    ("PPD Fullerene Fibers", None),
    ("Scandium Metallofullerene", None),
    ("", ""),
    # Boosters
    ("Booster Gases", ""),
    ("Amber Mykoserocin", None),
    ("Azure Mykoserocin", None),
    ("Celadon Mykoserocin", None),
    ("Golden Mykoserocin", None),
    ("Lime Mykoserocin", None),
    ("Malachite Mykoserocin", None),
    ("Vermillion Mykoserocin", None),
    ("Viridian Mykoserocin", None),
    ("Amber Cytoserocin", None),
    ("Azure Cytoserocin", None),
    ("Celadon Cytoserocin", None),
    ("Golden Cytoserocin", None),
    ("Lime Cytoserocin", None),
    ("Malachite Cytoserocin", None),
    ("Vermillion Cytoserocin", None),
    ("Viridian Cytoserocin", None),
    ("", ""),
    # PI
    ("Planetary Raw Materials (R0)", ""),
    ("Aqueous Liquids", None),
    ("Autotrophs", None),
    ("Base Metals", None),
    ("Carbon Compounds", None),
    ("Complex Organisms", None),
    ("Felsic Magma", None),
    ("Heavy Metals", None),
    ("Ionic Solutions", None),
    ("Micro Organisms", None),
    ("Noble Gas", None),
    ("Noble Metals", None),
    ("Non-CS Crystals", None),
    ("Planktic Colonies", None),
    ("Reactive Gas", None),
    ("Suspended Plasma", None),
    ("", ""),
    ("Planetary Processed Materials (P1)", ""),
    ("Bacteria", None),
    ("Biofuels", None),
    ("Biomass", None),
    ("Chiral Structures", None),
    ("Electrolytes", None),
    ("Industrial Fibers", None),
    ("Oxidizing Compound", None),
    ("Oxygen", None),
    ("Plasmoids", None),
    ("Precious Metals", None),
    ("Proteins", None),
    ("Reactive Metals", None),
    ("Silicon", None),
    ("Toxic Metals", None),
    ("Water", None),
    ("", ""),
    ("Planetary Refined Commodities (P2)", ""),
    ("Biocells", None),
    ("Construction Blocks", None),
    ("Consumer Electronics", None),
    ("Coolant", None),
    ("Enriched Uranium", None),
    ("Fertilizer", None),
    ("Genetically Enhanced Livestock", None),
    ("Livestock", None),
    ("Mechanical Parts", None),
    ("Microfiber Shielding", None),
    ("Miniature Electronics", None),
    ("Nanites", None),
    ("Oxides", None),
    ("Polyaramids", None),
    ("Polytextiles", None),
    ("Rocket Fuel", None),
    ("Silicate Glass", None),
    ("Superconductors", None),
    ("Supertensile Plastics", None),
    ("Synthetic Oil", None),
    ("Test Cultures", None),
    ("Transmitter", None),
    ("Viral Agent", None),
    ("Water-Cooled CPU", None),
    ("", ""),
    ("Planetary Specialized Commodities (P3)", ""),
    ("Biotech Research Reports", None),
    ("Camera Drones", None),
    ("Condensates", None),
    ("Cryoprotectant Solution", None),
    ("Data Chips", None),
    ("Gel-Matrix Biopaste", None),
    ("Guidance Systems", None),
    ("Hazmat Detection Systems", None),
    ("Hermetic Membranes", None),
    ("High-Tech Transmitters", None),
    ("Industrial Explosives", None),
    ("Neocoms", None),
    ("Nuclear Reactors", None),
    ("Planetary Vehicles", None),
    ("Robotics", None),
    ("Smartfab Units", None),
    ("Supercomputers", None),
    ("Synthetic Synapses", None),
    ("Transcranial Microcontrollers", None),
    ("Ukomi Super Conductors", None),
    ("Vaccines", None),
    ("", ""),
    ("Planetary Advanced Commodities (P4)", ""),
    ("Broadcast Node", None),
    ("Integrity Response Drones", None),
    ("Nano-Factory", None),
    ("Organic Mortar Applicators", None),
    ("Recursive Computing Module", None),
    ("Self-Harmonizing Power Core", None),
    ("Sterile Conduits", None),
    ("Wetware Mainframe", None),
    ]

TYPE_DATA_OLD = [
             ("Minerals", ""),
             ("Tritanium", None),
             ("Pyerite", None),
             ("Mexallon", None),
             ("Isogen", None),
             ("Nocxium", None),
             ("Zydrine", None),
             ("Megacyte", None),
             ("Morphite", None),
             ("", ""),
             ("Fuel", ""),
             ("Coolant", None),
             ("Enriched Uranium", None),
             ("Heavy Water", None),
             ("Helium Isotopes", None),
             ("Hydrogen Isotopes", None),
             ("Nitrogen Isotopes", None),
             ("Oxygen Isotopes", None),
             ("Liquid Ozone", None),
             ("Mechanical Parts", None),
             ("Oxygen", None),
             ("Robotics", None),
             ("Strontium Clathrates", None),
             ("", ""),
             ("Salvage Materials", ""),
             ("Alloyed Tritanium Bar", None),
             ("Armor Plates", None),
             ("Broken Drone Transceiver", None),
             ("Burned Logic Circuit", None),
             ("Charred Micro Circuit", None),
             ("Conductive Polymer", None),
             ("Contaminated Lorentz Fluid", None),
             ("Contaminated Nanite Compound", None),
             ("Damaged Artificial Neural Network", None),
             ("Defective Current Pump", None),
             ("Fried Interface Circuit", None),
             ("Malfunctioning Shield Emitter", None),
             ("Melted Capacitor Console", None),
             ("Scorched Telemetry Processor", None),
             ("Smashed Trigger Unit", None),
             ("Tangled Power Conduit", None),
             ("Thruster Console", None),
             ("Tripped Power Circuit", None),
             ("Ward Console", None),
             ("", ""),
             ("Datacores", ""),
             ("Datacore - Amarrian Starship Engineering", None),
             ("Datacore - Caldari Starship Engineering", None),
             ("Datacore - Electromagnetic Physics", None),
             ("Datacore - Electronic Engineering", None),
             ("Datacore - Gallentean Starship Engineering", None),
             ("Datacore - Graviton Physics", None),
             ("Datacore - High Energy Physics", None),
             ("Datacore - Hydromagnetic Physics", None),
             ("Datacore - Laser Physics", None),
             ("Datacore - Mechanical Engineering", None),
             ("Datacore - Minmatar Starship Engineering", None),
             ("Datacore - Molecular Engineering", None),
             ("Datacore - Nanite Engineering", None),
             ("Datacore - Nuclear Physics", None),
             ("Datacore - Plasma Physics", None),
             ("Datacore - Quantum Physics", None),
             ("Datacore - Rocket Science", None),
             ("", ""),
             ("Decryptors", ""),
             ("Advanced Theories", None),
             ("Assembly Instructions", None),
             ("Calibration Data", None),
             ("Circuitry Schematics", None),
             ("Circular Logic", None),
             ("Classic Doctrine", None),
             ("Collision Measurements", None),
             ("Engagement Plan", None),
             ("Formation Layout", None),
             ("Installation Guide", None),
             ("Interface Alignment Chart", None),
             ("Operation Handbook", None),
             ("Prototype Diagram", None),
             ("Sacred Manifesto", None),
             ("Stolen Formulas", None),
             ("Symbiotic Figures", None),
             ("Test Reports", None),
             ("Tuning Instructions", None),
             ("User Manual", None),
             ("War Strategon", None),
             ("", ""),
             ("Advanced Moon Minerals", ""),
             ("Crystalline Carbonide", None),
             ("Fermionic Condensates", None),
             ("Fernite Carbide", None),
             ("Ferrogel", None),
             ("Fullerides", None),
             ("Hypersynaptic Fibers", None),
             ("Nanotransistors", None),
             ("Phenolic Composites", None),
             ("Sylramic Fibers", None),
             ("Titanium Carbide", None),
             ("Tungsten Carbide", None),
             ("", ""),
             ("Ancient Salvaged Materials", ""),
             ("Cartesian Temporal Coordinator", None),
             ("Central System Controller", None),
             ("Defensive Control Node", None),
             ("Electromechanical Hull Sheeting", None),
             ("Emergent Combat Analyzer", None),
             ("Emergent Combat Intelligence", None),
             ("Fused Nanomechanical Engines", None),
             ("Heuristic Selfassemblers", None),
             ("Jump Drive Control Nexus", None),
             ("Melted Nanoribbons", None),
             ("Modified Fluid Router", None),
             ("Neurovisual Input Matrix", None),
             ("Powdered C-540 Graphite", None),
             ("Resonance Calibration Matrix", None),
             ("Thermoelectric Catalysts", None),
             ("", ""),
             ("Ancient Relics", ""),
             ("Intact Armor Nanobot", None),
             ("Intact Electromechanical Component", None),
             ("Intact Hull Section", None),
             ("Intact Power Cores", None),
             ("Intact Thruster Sections", None),
             ("Intact Weapon Subroutines", None),
             ("Malfunctioning Armor Nanobot", None),
             ("Malfunctioning Electromechanical Component", None),
             ("Malfunctioning Hull Section", None),
             ("Malfunctioning Power Cores", None),
             ("Malfunctioning Thruster Sections", None),
             ("Malfunctioning Weapon Subroutines", None),
             ("Wrecked Armor Nanobot", None),
             ("Wrecked Electromechanical Component", None),
             ("Wrecked Hull Section", None),
             ("Wrecked Power Cores", None),
             ("Wrecked Thruster Sections", None),
             ("Wrecked Weapon Subroutines", None),
             ("", ""),
             ("Hybrid Datacores", ""),
             ("Datacore - Defensive Subsystems Engineering", None),
             ("Datacore - Electronic Subsystems Engineering", None),
             ("Datacore - Engineering Subsystems Engineering", None),
             ("Datacore - Offensive Subsystems Engineering", None),
             ("Datacore - Propulsion Subsystems Engineering", None),
             ("", ""),
             ("Hybrid Decryptors", ""),
             ("R.A.M.- Hybrid Technology", None),
             ("Amarr Hybrid Tech Decryptor", None),
             ("Caldari Hybrid Tech Decryptor", None),
             ("Gallente Hybrid Tech Decryptor", None),
             ("Minmatar Hybrid Tech Decryptor", None),
             ("", ""),
             ("Fullerenes", ""),
             ("Fullerite-C28", None),
             ("Fullerite-C32", None),
             ("Fullerite-C50", None),
             ("Fullerite-C60", None),
             ("Fullerite-C70", None),
             ("Fullerite-C72", None),
             ("Fullerite-C84", None),
             ("Fullerite-C320", None),
             ("Fullerite-C540", None),
             ("", ""),
             ("Hybrid Polymers", ""),
             ("C3-FTM Acid", None),
             ("Carbon-86 Epoxy Resin", None),
             ("Fullerene Intercalated Graphite", None),
             ("Fulleroferrocene", None),
             ("Graphene Nanoribbons", None),
             ("Lanthanum Metallofullerene", None),
             ("Methanofullerene", None),
             ("PPD Fullerene Fibers", None),
             ("Scandium Metallofullerene", None),
             ("", ""),
             ("Moon Raw Materials", ""),
             ("Atmospheric Gases", None),
             ("Cadmium", None),
             ("Caesium", None),
             ("Chromium", None),
             ("Cobalt", None),
             ("Dysprosium", None),
             ("Evaporite Deposits", None),
             ("Hafnium", None),
             ("Hydrocarbons", None),
             ("Mercury", None),
             ("Neodymium", None),
             ("Platinum", None),
             ("Promethium", None),
             ("Scandium", None),
             ("Silicates", None),
             ("Technetium", None),
             ("Thulium", None),
             ("Titanium", None),
             ("Tungsten", None),
             ("Vanadium", None),
             ("", ""),
             ("Processed Materials", ""),
             ("Sulfuric Acid", None),
             ("Silicon Diborite", None),
             ("Ceramic Powder", None),
             ("Carbon Polymers", None),
             ("Crystallite Alloy", None),
             ("Fernite Alloy", None),
             ("Titanium Chromide", None),
             ("Rolled Tungsten Alloy", None),
             ("Hexite", None),
             ("Caesarium Cadmide", None),
             ("Solerium", None),
             ("Platinum Technite", None),
             ("Vanadium Hafnite", None),
             ("Prometium", None),
             ("Hyperflurite", None),
             ("Ferrofluid", None),
             ("Dysporite", None),
             ("Neo Mercurite", None),
             ("Fluxed Condensates", None),
             ("", ""),
             ("Tech 2 Salvage Materials", ""),
             ("Artificial Neural Network", None),
             ("Capacitor Console", None),
             ("Conductive Thermoplastic", None),
             ("Current Pump", None),
             ("Drone Transceiver", None),
             ("Enhanced Ward Console", None),
             ("Impetus Console", None),
             ("Intact Armor Plates", None),
             ("Intact Shield Emitter", None),
             ("Interface Circuit", None),
             ("Logic Circuit", None),
             ("Lorentz Fluid", None),
             ("Micro Circuit", None),
             ("Nanite Compound", None),
             ("Power Circuit", None),
             ("Power Conduit", None),
             ("Single-crystal Superalloy I-beam", None),
             ("Telemetry Processor", None),
             ("Trigger Unit", None),
             ("", ""),
             ("Booster Gases", ""),
             ("Amber Mykoserocin", None),
             ("Azure Mykoserocin", None),
             ("Celadon Mykoserocin", None),
             ("Golden Mykoserocin", None),
             ("Lime Mykoserocin", None),
             ("Malachite Mykoserocin", None),
             ("Vermillion Mykoserocin", None),
             ("Viridian Mykoserocin", None),
             ("Amber Cytoserocin", None),
             ("Azure Cytoserocin", None),
             ("Celadon Cytoserocin", None),
             ("Golden Cytoserocin", None),
             ("Lime Cytoserocin", None),
             ("Malachite Cytoserocin", None),
             ("Vermillion Cytoserocin", None),
             ("Viridian Cytoserocin", None),
             ("", ""),
             ("Tech 2 Production", ""),
             ("Construction Blocks", None),
             ("Electronic Parts", None),
             ("Guidance Systems", None),
             ("Hydrogen Batteries", None),
             ("Miniature Electronics", None),
             ("Rocket Fuel", None),
             ("Superconductors", None),
             ("Transmitter", None),
             ("", ""),
             ("Planetary Raw Materials", ""),
             ("Aqueous Liquids", None),
             ("Autotrophs", None),
             ("Base Metals", None),
             ("Carbon Compounds", None),
             ("Complex Organisms", None),
             ("Felsic Magma", None),
             ("Heavy Metals", None),
             ("Ionic Solutions", None),
             ("Micro Organisms", None),
             ("Noble Gas", None),
             ("Noble Metals", None),
             ("Non-CS Crystals", None),
             ("Planktic Colonies", None),
             ("Reactive Gas", None),
             ("Suspended Plasma", None),
             ("", ""),
             ("Planetary Advanced Commodities", ""),
             ("Broadcast Node", None),
             ("Integrity Response Drones", None),
             ("Nano-Factory", None),
             ("Organic Mortar Applicators", None),
             ("Recursive Computing Module", None),
             ("Self-Harmonizing Power Core", None),
             ("Sterile Conduits", None),
             ("Wetware Mainframe", None),
             ]

# def current():
#     """
#     Return a dictionary of current index prices.
#     """
#     return dict((row[0], IndexRow(row))
#                 for row
#                 in csv.reader(file(os.path.join(LOCALDIR, "current.txt")))
#                 if row[1] not in ("", "Index"))

# class IndexRow(float):
#     def __new__(cls, row):
#         obj = super(IndexRow, cls).__new__(cls, row[1])
#         (obj.name, obj.index, obj.change,  obj.movement,
#          obj.heimatar, obj.metropolis, obj.moldenheath,
#          obj.jita) = row
#         obj.index = float(obj.index)
#         obj.change = float(obj.change[:-1])/100
#         obj.movement = long(obj.movement)
#         obj.heimatar = float(obj.heimatar)
#         obj.metropolis = float(obj.metropolis)
#         obj.moldenheath = float(obj.moldenheath)
#         obj.jita = float(obj.jita)
#         return obj

