TYPE_DATA = [
    # T1
    ## Minerals
    ("Minerals", "header"),
    ("Tritanium", "typename"),
    ("Pyerite", "typename"),
    ("Mexallon", "typename"),
    ("Isogen", "typename"),
    ("Nocxium", "typename"),
    ("Zydrine", "typename"),
    ("Megacyte", "typename"),
    ("Morphite", "typename"),
    # Rigs
    ## Tech 1 rigs
    ("Salvage Materials", "header"),
    ("Alloyed Tritanium Bar", "typename"),
    ("Armor Plates", "typename"),
    ("Broken Drone Transceiver", "typename"),
    ("Burned Logic Circuit", "typename"),
    ("Charred Micro Circuit", "typename"),
    ("Conductive Polymer", "typename"),
    ("Contaminated Lorentz Fluid", "typename"),
    ("Contaminated Nanite Compound", "typename"),
    ("Damaged Artificial Neural Network", "typename"),
    ("Defective Current Pump", "typename"),
    ("Fried Interface Circuit", "typename"),
    ("Malfunctioning Shield Emitter", "typename"),
    ("Melted Capacitor Console", "typename"),
    ("Scorched Telemetry Processor", "typename"),
    ("Smashed Trigger Unit", "typename"),
    ("Tangled Power Conduit", "typename"),
    ("Thruster Console", "typename"),
    ("Tripped Power Circuit", "typename"),
    ("Ward Console", "typename"),
    ## Tech 2 rigs
    ("Tech 2 Salvage Materials", "header"),
    ("Artificial Neural Network", "typename"),
    ("Capacitor Console", "typename"),
    ("Conductive Thermoplastic", "typename"),
    ("Current Pump", "typename"),
    ("Drone Transceiver", "typename"),
    ("Enhanced Ward Console", "typename"),
    ("Impetus Console", "typename"),
    ("Intact Armor Plates", "typename"),
    ("Intact Shield Emitter", "typename"),
    ("Interface Circuit", "typename"),
    ("Logic Circuit", "typename"),
    ("Lorentz Fluid", "typename"),
    ("Micro Circuit", "typename"),
    ("Nanite Compound", "typename"),
    ("Power Circuit", "typename"),
    ("Power Conduit", "typename"),
    ("Single-crystal Superalloy I-beam", "typename"),
    ("Telemetry Processor", "typename"),
    ("Trigger Unit", "typename"),
    # POS stuff
    ## Ice products
    ("Ice Products", "header"),
    ("Helium Isotopes", "typename"),
    ("Hydrogen Isotopes", "typename"),
    ("Nitrogen Isotopes", "typename"),
    ("Oxygen Isotopes", "typename"),
    ("Heavy Water", "typename"),
    ("Liquid Ozone", "typename"),
    ("Strontium Clathrates", "typename"),
    ## PI products
    ("Starbase Fuel", "header"),
    ("Coolant", "typename"),
    ("Enriched Uranium", "typename"),
    ("Mechanical Parts", "typename"),
    ("Oxygen", "typename"),
    ("Robotics", "typename"),
    # T2
    ## Datacores
    ("Datacores", "header"),
    ("Datacore - Amarrian Starship Engineering", "typename"),
    ("Datacore - Caldari Starship Engineering", "typename"),
    ("Datacore - Electromagnetic Physics", "typename"),
    ("Datacore - Electronic Engineering", "typename"),
    ("Datacore - Gallentean Starship Engineering", "typename"),
    ("Datacore - Graviton Physics", "typename"),
    ("Datacore - High Energy Physics", "typename"),
    ("Datacore - Hydromagnetic Physics", "typename"),
    ("Datacore - Laser Physics", "typename"),
    ("Datacore - Mechanical Engineering", "typename"),
    ("Datacore - Minmatar Starship Engineering", "typename"),
    ("Datacore - Molecular Engineering", "typename"),
    ("Datacore - Nanite Engineering", "typename"),
    ("Datacore - Nuclear Physics", "typename"),
    ("Datacore - Plasma Physics", "typename"),
    ("Datacore - Quantum Physics", "typename"),
    ("Datacore - Rocket Science", "typename"),
    ## Decryptors
    ("Decryptors", "header"),
    ("Advanced Theories", "typename"),
    ("Assembly Instructions", "typename"),
    ("Calibration Data", "typename"),
    ("Circuitry Schematics", "typename"),
    ("Circular Logic", "typename"),
    ("Classic Doctrine", "typename"),
    ("Collision Measurements", "typename"),
    ("Engagement Plan", "typename"),
    ("Formation Layout", "typename"),
    ("Installation Guide", "typename"),
    ("Interface Alignment Chart", "typename"),
    ("Operation Handbook", "typename"),
    ("Prototype Diagram", "typename"),
    ("Sacred Manifesto", "typename"),
    ("Stolen Formulas", "typename"),
    ("Symbiotic Figures", "typename"),
    ("Test Reports", "typename"),
    ("Tuning Instructions", "typename"),
    ("User Manual", "typename"),
    ("War Strategon", "typename"),
    ## Moon materials
    ("Raw Moon Materials", "header"),
    ("Atmospheric Gases", "typename"),
    ("Cadmium", "typename"),
    ("Caesium", "typename"),
    ("Chromium", "typename"),
    ("Cobalt", "typename"),
    ("Dysprosium", "typename"),
    ("Evaporite Deposits", "typename"),
    ("Hafnium", "typename"),
    ("Hydrocarbons", "typename"),
    ("Mercury", "typename"),
    ("Neodymium", "typename"),
    ("Platinum", "typename"),
    ("Promethium", "typename"),
    ("Scandium", "typename"),
    ("Silicates", "typename"),
    ("Technetium", "typename"),
    ("Thulium", "typename"),
    ("Titanium", "typename"),
    ("Tungsten", "typename"),
    ("Vanadium", "typename"),
    ## Simple reactions
    ("Processed Moon Materials", "header"),
    ("Caesarium Cadmide", "typename"),
    ("Carbon Polymers", "typename"),
    ("Ceramic Powder", "typename"),
    ("Crystallite Alloy", "typename"),
    ("Dysporite", "typename"),
    ("Fernite Alloy", "typename"),
    ("Ferrofluid", "typename"),
    ("Fluxed Condensates", "typename"),
    ("Hexite", "typename"),
    ("Hyperflurite", "typename"),
    ("Neo Mercurite", "typename"),
    ("Platinum Technite", "typename"),
    ("Prometium", "typename"),
    ("Rolled Tungsten Alloy", "typename"),
    ("Silicon Diborite", "typename"),
    ("Solerium", "typename"),
    ("Sulfuric Acid", "typename"),
    ("Titanium Chromide", "typename"),
    ("Vanadium Hafnite", "typename"),
    ## Complex reactions
    ("Advanced Moon Materials", "header"),
    ("Crystalline Carbonide", "typename"),
    ("Fermionic Condensates", "typename"),
    ("Fernite Carbide", "typename"),
    ("Ferrogel", "typename"),
    ("Fullerides", "typename"),
    ("Hypersynaptic Fibers", "typename"),
    ("Nanotransistors", "typename"),
    ("Phenolic Composites", "typename"),
    ("Sylramic Fibers", "typename"),
    ("Titanium Carbide", "typename"),
    ("Tungsten Carbide", "typename"),
    ## Moon final products
    ("Tech 2 Construction Components", "header"),
    ("Antimatter Reactor Unit", "typename"),
    ("Crystalline Carbonide Armor Plate", "typename"),
    ("Deflection Shield Emitter", "typename"),
    ("Electrolytic Capacitor Unit", "typename"),
    ("Emp Pulse Generator", "typename"),
    ("Fernite Carbide Composite Armor Plate", "typename"),
    ("Fusion Reactor Unit", "typename"),
    ("Fusion Thruster", "typename"),
    ("Gravimetric Sensor Cluster", "typename"),
    ("Graviton Pulse Generator", "typename"),
    ("Graviton Reactor Unit", "typename"),
    ("Ion Thruster", "typename"),
    ("Ladar Sensor Cluster", "typename"),
    ("Laser Focusing Crystals", "typename"),
    ("Linear Shield Emitter", "typename"),
    ("Magnetometric Sensor Cluster", "typename"),
    ("Magpulse Thruster", "typename"),
    ("Nanoelectrical Microprocessor", "typename"),
    ("Nanomechanical Microprocessor", "typename"),
    ("Nuclear Pulse Generator", "typename"),
    ("Nuclear Reactor Unit", "typename"),
    ("Oscillator Capacitor Unit", "typename"),
    ("Particle Accelerator Unit", "typename"),
    ("Photon Microprocessor", "typename"),
    ("Plasma Pulse Generator", "typename"),
    ("Plasma Thruster", "typename"),
    ("Pulse Shield Emitter", "typename"),
    ("Quantum Microprocessor", "typename"),
    ("Radar Sensor Cluster", "typename"),
    ("Scalar Capacitor Unit", "typename"),
    ("Superconductor Rails", "typename"),
    ("Sustained Shield Emitter", "typename"),
    ("Tesseract Capacitor Unit", "typename"),
    ("Thermonuclear Trigger Unit", "typename"),
    ("Titanium Diborite Armor Plate", "typename"),
    ("Tungsten Carbide Armor Plate", "typename"),
    ## PI products for T2
    ("Tech 2 Production", "header"),
    ("Construction Blocks", "typename"),
    ("Electronic Parts", "typename"),
    ("Guidance Systems", "typename"),
    ("Hydrogen Batteries", "typename"),
    ("Miniature Electronics", "typename"),
    ("Rocket Fuel", "typename"),
    ("Superconductors", "typename"),
    ("Transmitter", "typename"),
    # T3
    ## Ancient Salvage
    ("Ancient Salvaged Materials", "header"),
    ("Cartesian Temporal Coordinator", "typename"),
    ("Central System Controller", "typename"),
    ("Defensive Control Node", "typename"),
    ("Electromechanical Hull Sheeting", "typename"),
    ("Emergent Combat Analyzer", "typename"),
    ("Emergent Combat Intelligence", "typename"),
    ("Fused Nanomechanical Engines", "typename"),
    ("Heuristic Selfassemblers", "typename"),
    ("Jump Drive Control Nexus", "typename"),
    ("Melted Nanoribbons", "typename"),
    ("Modified Fluid Router", "typename"),
    ("Neurovisual Input Matrix", "typename"),
    ("Powdered C-540 Graphite", "typename"),
    ("Resonance Calibration Matrix", "typename"),
    ("Thermoelectric Catalysts", "typename"),
    ## Ancient Relics
    ("Ancient Relics", "header"),
    ("Intact Armor Nanobot", "typename"),
    ("Intact Electromechanical Component", "typename"),
    ("Intact Hull Section", "typename"),
    ("Intact Power Cores", "typename"),
    ("Intact Thruster Sections", "typename"),
    ("Intact Weapon Subroutines", "typename"),
    ("Malfunctioning Armor Nanobot", "typename"),
    ("Malfunctioning Electromechanical Component", "typename"),
    ("Malfunctioning Hull Section", "typename"),
    ("Malfunctioning Power Cores", "typename"),
    ("Malfunctioning Thruster Sections", "typename"),
    ("Malfunctioning Weapon Subroutines", "typename"),
    ("Wrecked Armor Nanobot", "typename"),
    ("Wrecked Electromechanical Component", "typename"),
    ("Wrecked Hull Section", "typename"),
    ("Wrecked Power Cores", "typename"),
    ("Wrecked Thruster Sections", "typename"),
    ("Wrecked Weapon Subroutines", "typename"),
    ## Datacores
    ("Hybrid Datacores", "header"),
    ("Datacore - Defensive Subsystems Engineering", "typename"),
    ("Datacore - Electronic Subsystems Engineering", "typename"),
    ("Datacore - Engineering Subsystems Engineering", "typename"),
    ("Datacore - Offensive Subsystems Engineering", "typename"),
    ("Datacore - Propulsion Subsystems Engineering", "typename"),
    ## Decryptors
    ("Hybrid Decryptors", "header"),
    ("R.A.M.- Hybrid Technology", "typename"),
    ("Amarr Hybrid Tech Decryptor", "typename"),
    ("Caldari Hybrid Tech Decryptor", "typename"),
    ("Gallente Hybrid Tech Decryptor", "typename"),
    ("Minmatar Hybrid Tech Decryptor", "typename"),
    ## Gas
    ("Fullerenes", "header"),
    ("Fullerite-C28", "typename"),
    ("Fullerite-C32", "typename"),
    ("Fullerite-C50", "typename"),
    ("Fullerite-C60", "typename"),
    ("Fullerite-C70", "typename"),
    ("Fullerite-C72", "typename"),
    ("Fullerite-C84", "typename"),
    ("Fullerite-C320", "typename"),
    ("Fullerite-C540", "typename"),
    ## Polymers
    ("Hybrid Polymers", "header"),
    ("C3-FTM Acid", "typename"),
    ("Carbon-86 Epoxy Resin", "typename"),
    ("Fullerene Intercalated Graphite", "typename"),
    ("Fulleroferrocene", "typename"),
    ("Graphene Nanoribbons", "typename"),
    ("Lanthanum Metallofullerene", "typename"),
    ("Methanofullerene", "typename"),
    ("PPD Fullerene Fibers", "typename"),
    ("Scandium Metallofullerene", "typename"),
    # Boosters
    ("Booster Gases", "header"),
    ("Amber Mykoserocin", "typename"),
    ("Azure Mykoserocin", "typename"),
    ("Celadon Mykoserocin", "typename"),
    ("Golden Mykoserocin", "typename"),
    ("Lime Mykoserocin", "typename"),
    ("Malachite Mykoserocin", "typename"),
    ("Vermillion Mykoserocin", "typename"),
    ("Viridian Mykoserocin", "typename"),
    ("Amber Cytoserocin", "typename"),
    ("Azure Cytoserocin", "typename"),
    ("Celadon Cytoserocin", "typename"),
    ("Golden Cytoserocin", "typename"),
    ("Lime Cytoserocin", "typename"),
    ("Malachite Cytoserocin", "typename"),
    ("Vermillion Cytoserocin", "typename"),
    ("Viridian Cytoserocin", "typename"),
    # PI
    ## R0
    ("Planetary Raw Materials (R0)", "header"),
    ("Aqueous Liquids", "typename"),
    ("Autotrophs", "typename"),
    ("Base Metals", "typename"),
    ("Carbon Compounds", "typename"),
    ("Complex Organisms", "typename"),
    ("Felsic Magma", "typename"),
    ("Heavy Metals", "typename"),
    ("Ionic Solutions", "typename"),
    ("Micro Organisms", "typename"),
    ("Noble Gas", "typename"),
    ("Noble Metals", "typename"),
    ("Non-CS Crystals", "typename"),
    ("Planktic Colonies", "typename"),
    ("Reactive Gas", "typename"),
    ("Suspended Plasma", "typename"),
    ## P1
    ("Planetary Processed Materials (P1)", "header"),
    ("Bacteria", "typename"),
    ("Biofuels", "typename"),
    ("Biomass", "typename"),
    ("Chiral Structures", "typename"),
    ("Electrolytes", "typename"),
    ("Industrial Fibers", "typename"),
    ("Oxidizing Compound", "typename"),
    ("Oxygen", "typename"),
    ("Plasmoids", "typename"),
    ("Precious Metals", "typename"),
    ("Proteins", "typename"),
    ("Reactive Metals", "typename"),
    ("Silicon", "typename"),
    ("Toxic Metals", "typename"),
    ("Water", "typename"),
    ## P2
    ("Planetary Refined Commodities (P2)", "header"),
    ("Biocells", "typename"),
    ("Construction Blocks", "typename"),
    ("Consumer Electronics", "typename"),
    ("Coolant", "typename"),
    ("Enriched Uranium", "typename"),
    ("Fertilizer", "typename"),
    ("Genetically Enhanced Livestock", "typename"),
    ("Livestock", "typename"),
    ("Mechanical Parts", "typename"),
    ("Microfiber Shielding", "typename"),
    ("Miniature Electronics", "typename"),
    ("Nanites", "typename"),
    ("Oxides", "typename"),
    ("Polyaramids", "typename"),
    ("Polytextiles", "typename"),
    ("Rocket Fuel", "typename"),
    ("Silicate Glass", "typename"),
    ("Superconductors", "typename"),
    ("Supertensile Plastics", "typename"),
    ("Synthetic Oil", "typename"),
    ("Test Cultures", "typename"),
    ("Transmitter", "typename"),
    ("Viral Agent", "typename"),
    ("Water-Cooled CPU", "typename"),
    ## P3
    ("Planetary Specialized Commodities (P3)", "header"),
    ("Biotech Research Reports", "typename"),
    ("Camera Drones", "typename"),
    ("Condensates", "typename"),
    ("Cryoprotectant Solution", "typename"),
    ("Data Chips", "typename"),
    ("Gel-Matrix Biopaste", "typename"),
    ("Guidance Systems", "typename"),
    ("Hazmat Detection Systems", "typename"),
    ("Hermetic Membranes", "typename"),
    ("High-Tech Transmitters", "typename"),
    ("Industrial Explosives", "typename"),
    ("Neocoms", "typename"),
    ("Nuclear Reactors", "typename"),
    ("Planetary Vehicles", "typename"),
    ("Robotics", "typename"),
    ("Smartfab Units", "typename"),
    ("Supercomputers", "typename"),
    ("Synthetic Synapses", "typename"),
    ("Transcranial Microcontrollers", "typename"),
    ("Ukomi Super Conductors", "typename"),
    ("Vaccines", "typename"),
    ## P4
    ("Planetary Advanced Commodities (P4)", "header"),
    ("Broadcast Node", "typename"),
    ("Integrity Response Drones", "typename"),
    ("Nano-Factory", "typename"),
    ("Organic Mortar Applicators", "typename"),
    ("Recursive Computing Module", "typename"),
    ("Self-Harmonizing Power Core", "typename"),
    ("Sterile Conduits", "typename"),
    ("Wetware Mainframe", "typename"),
    ]

REFINEABLES_DATA = [
    # Asteroids
    ("Ore (Refined)", "header"),

    ("Veldspar", "typename"),
    ("Concentrated Veldspar", "typename"),
    ("Dense Veldspar", "typename"),

    ("Scordite", "typename"),
    ("Condensed Scordite", "typename"),
    ("Massive Scordite", "typename"),

    ("Pyroxeres", "typename"),
    ("Solid Pyroxeres", "typename"),
    ("Viscous Pyroxeres", "typename"),

    ("Plagioclase", "typename"),
    ("Azure Plagioclase", "typename"),
    ("Rich Plagioclase", "typename"),

    ("Omber", "typename"),
    ("Silvery Omber", "typename"),
    ("Golden Omber", "typename"),

    ("Kernite", "typename"),
    ("Luminous Kernite", "typename"),
    ("Fiery Kernite", "typename"),

    ("Jaspet", "typename"),
    ("Pure Jaspet", "typename"),
    ("Pristine Jaspet", "typename"),

    ("Hemorphite", "typename"),
    ("Vivid Hemorphite", "typename"),
    ("Radiant Hemorphite", "typename"),

    ("Hedbergite", "typename"),
    ("Vitric Hedbergite", "typename"),
    ("Glazed Hedbergite", "typename"),

    ("Gneiss", "typename"),
    ("Iridescent Gneiss", "typename"),
    ("Prismatic Gneiss", "typename"),

    ("Dark Ochre", "typename"),
    ("Onyx Ochre", "typename"),
    ("Obsidian Ochre", "typename"),

    ("Crokite", "typename"),
    ("Sharp Crokite", "typename"),
    ("Crystalline Crokite", "typename"),

    ("Spodumain", "typename"),
    ("Bright Spodumain", "typename"),
    ("Gleaming Spodumain", "typename"),

    ("Bistot", "typename"),
    ("Triclinic Bistot", "typename"),
    ("Monoclinic Bistot", "typename"),

    ("Arkonor", "typename"),
    ("Crimson Arkonor", "typename"),
    ("Prime Arkonor", "typename"),

    ("Mercoxit", "typename"),
    ("Magma Mercoxit", "typename"),
    ("Vitreous Mercoxit", "typename"),

    # Ice
    ("Ice (Refined)", "header"),

    ("Glacial Mass", "typename"),
    ("Smooth Glacial Mass", "typename"),
    ("Blue Ice", "typename"),
    ("Thick Blue Ice", "typename"),
    ("White Glaze", "typename"),
    ("Pristine White Glaze", "typename"),
    ("Clear Icicle", "typename"),
    ("Enriched Clear Icicle", "typename"),

    ("Krystallos", "typename"),
    ("Glare crust", "typename"),
    ("Gelidus", "typename"),
    ("Dark Glitter", "typename"),

    # Drone alloys
    ("Alloys & Compounds (Refined)", "header"),
    ("Condensed Alloy", "typename"),
    ("Crystal Compound", "typename"),
    ("Precious Alloy", "typename"),
    ("Gleaming Alloy", "typename"),
    ("Sheen Compound", "typename"),
    ("Lucent Compound", "typename"),
    ("Dark Compound", "typename"),
    ("Motley Compound", "typename"),
    ("Lustering Alloy", "typename"),
    ("Plush Compound", "typename"),
    ("Glossy Compound", "typename"),
    ("Opulent Compound", "typename"),
]
