#!/usr/bin/env python

import evelib.api as api

def main():
    grd = api.corp()
    gms = grd.MemberSecurity()
    members = list(gms.member)
    members.sort(lambda a, b: cmp(a.name.lower(), b.name.lower()))
    for member in members:
        titles = [x.titleName for x in member.titles]
        roles = [x.roleName for x in member.roles]
        if 'roleDirector' in roles:
            roles.remove('roleDirector')
            titles.append('Director')
        if len(roles) > 0:
            print "%s has direct roles: %s" % (member.name, ", ".join(roles))
        if 'Director' not in titles and 'Employee' not in titles and 'Prospect' not in titles:
            print "%s is missing a base title (Prospect, Employee, Director): %s" % (member.name, ", ".join(titles))
    # gmt = grd.MemberTracking()

if __name__ == '__main__':
    main()
