#!/bin/sh

FILE="$1"

if [ -z "$FILE" ]
then
    program=`basename "$0"`
    echo "usage: $program <dump.sql.bz2>"
    exit 1
fi

( echo "DROP SCHEMA ccp CASCADE;"
  echo "CREATE SCHEMA ccp;"
  echo "SET search_path TO ccp, pg_catalog;"
  cat "$FILE" | bunzip2 | grep -v "SET search_path"
) | psql eve
