#!/usr/bin/env python

import evelib.newdb as db
from sdb.orm import O

def main():
    conn = db.connect()
    c = conn.cursor()
    bad_pilots = [x.strip() for x in file("/home/forcer/Depot/EVE/badpilots.txt")]
    q = ("SELECT id FROM ki_pilot WHERE name IN " + O(bad_pilots))
    c.execute(q.operation, q.parameters)
    bad_ids = [x.id for x in c.fetchall()]
    q = ("UPDATE killinfo SET isfake = 't' "
         "WHERE date > '2010-07-20' "
         "  AND NOT isfake "
         "  AND victim_id IN " + O(bad_ids) +
         "  AND NOT EXISTS (SELECT id FROM ki_involved inv " 
         "                  WHERE inv.kill_id = killinfo.id " 
         "                    AND name_id NOT IN " + O(bad_ids) +
         "                 )")
    c.execute(q.operation, q.parameters)
    print "Marked %i mails as fake (PL)." % c.rowcount
    q = ("UPDATE killinfo SET isfake = 't' "
         "WHERE NOT isfake "
         "  AND id IN (SELECT kill_id "
         "             FROM ki_involved "
         "             WHERE NOT isnpc "
         "             GROUP BY kill_id, name_id "
         "             HAVING COUNT(*) > 1)")
    c.execute(q)
    print "Marked %i mails as fake (duplicate non-NPC involved)." % c.rowcount
    q = ("UPDATE killinfo SET isfake = 't' "
         "WHERE NOT isfake "
         "  AND id IN (SELECT kill_id "
         "             FROM ki_item "
         "             WHERE quantity = 2147483647) ")
    c.execute(q)
    print "Marked %i mails as fake (too many items)." % c.rowcount
    conn.commit()

if __name__ == '__main__':
    main()
