#!/usr/bin/env python

import evelib.newdb as db

conn = db.connect()
c = conn.cursor()
c.execute("""
SELECT count(*) AS kills,
       NAME
FROM (SELECT ki.id AS killid,
             COALESCE(a.name, c.name) AS name
      FROM ki_involved inv
           INNER JOIN killinfo ki ON inv.kill_id = ki.id
           LEFT JOIN ki_alliance a ON inv.alliance_id = a.id
           INNER JOIN ki_corp c ON inv.corp_id = c.id
           INNER JOIN ki_system ks ON ki.system_id = ks.id
           INNER JOIN ccp.mapsolarsystems sys
             ON ks.externalid = sys.solarsystemid
           INNER JOIN ccp.mapregions reg ON sys.regionid = reg.regionid
      WHERE ki.date > NOW() - INTERVAL '28 days'
        AND NOT inv.isnpc
        AND reg.regionname IN ('Metropolis', 'Heimatar', 'Molden Heath')
        AND sys.security >= 0.45
      GROUP BY ki.id, COALESCE(a.name, c.name)) AS sq
GROUP BY name
ORDER BY kills DESC
LIMIT 20
""")
for rank, (kills, name) in enumerate(c.fetchall()):
    print "%2i. %s (%s kills)" % (rank + 1, name, kills)
