#!/usr/bin/env python

import csv
import datetime
import StringIO

import evelib.newdb as db
import evelib.api as api

from evelib.util import humane
import emcom.ftp as ftp

PRODUCERS = {'Isobel Mitar':
                 {'Pator VII (Kulheim) - Republic Security Services Assembly Plant':
                      ['Advanced Mobile Laboratory',
                       'Badger Mark II',
                       'Ballistic Deflection Array',
                       'Bellicose',
                       'Blackbird',
                       'Bomb Launcher I',
                       'Brutix',
                       'Caldari Control Tower',
                       'Caldari Control Tower Medium',
                       'Caldari Control Tower Small',
                       'Caracal',
                       'Catalyst',
                       'Celestis',
                       'Complex Reactor Array',
                       'Cormorant',
                       'Corporate Hangar Array',
                       'Cyclone',
                       'Dominix',
                       'Drake',
                       'Energy Neutralizing Battery',
                       'Exequror',
                       'Explosion Dampening Array',
                       'Ferox',
                       'Heat Dissipation Array',
                       'Hurricane',
                       'Ion Field Projection Battery',
                       'Iteron Mark IV',
                       'Large Artillery Battery',
                       'Large AutoCannon Battery',
                       'Maelstrom',
                       'Mammoth',
                       'Medium Artillery Battery',
                       'Medium AutoCannon Battery',
                       'Megathron',
                       'Minmatar Control Tower',
                       'Minmatar Control Tower Medium',
                       'Minmatar Control Tower Small',
                       'Minmatar Shuttle',
                       'Moa',
                       'Mobile Laboratory',
                       'Moon Harvesting Array',
                       'Myrmidon',
                       'Noctis',
                       'Osprey',
                       'Phase Inversion Battery',
                       'Photon Scattering Array',
                       'Probe',
                       'Raven',
                       'Rifter',
                       'Rupture',
                       'Scorpion',
                       'Scythe',
                       'Ship Maintenance Array',
                       'Silo',
                       'Simple Reactor Array',
                       'Small Artillery Battery',
                       'Small AutoCannon Battery',
                       'Spatial Destabilization Battery',
                       'Stabber',
                       'Stasis Webification Battery',
                       'Tempest',
                       'Thorax',
                       'Thrasher',
                       'Typhoon',
                       'Vexor',
                       'Warp Disruption Battery',
                       'Warp Scrambling Battery',
                       'White Noise Generation Battery',
                       ]
                  },
             'Arkady Sadik':
                 {'Dal III - Moon 1 - Republic Fleet Assembly Plant':
                      # Ships
                      ['Stabber', 'Thrasher', 'Rifter',
                       'Caracal', 'Griffin',
                       # Projectile ammo
                       'EMP L', 'EMP M', 'EMP S',
                       'Fusion L', 'Fusion M', 'Fusion S',
                       'Phased Plasma L', 'Phased Plasma M', 'Phased Plasma S',
                       # Cruise Missiles
                       'Cataclysm Cruise Missile', 'Paradise Cruise Missile',
                       'Wrath Cruise Missile', 'Devastator Cruise Missile',
                       # Torpedos
                       'Juggernaut Torpedo', 'Bane Torpedo',
                       'Inferno Torpedo', 'Mjolnir Torpedo',
                       # Heavy Missiles
                       'Scourge Heavy Missile', 'Havoc Heavy Missile',
                       'Thunderbolt Heavy Missile', 'Widowmaker Heavy Missile',
                       # Heavy Assault Missiles
                       'Fulmination Assault Missile',
                       'Hellfire Assault Missile',
                       'Terror Assault Missile',
                       # Light missiles
                       'Sabretooth Light Missile', 'Bloodclaw Light Missile',
                       'Flameburst Light Missile', 'Piranha Light Missile',
                       # Rockets
                       'Foxfire Rocket', 'Gremlin Rocket',
                       'Phalanx Rocket',
                       # Rigs
                       'Medium Capacitor Control Circuit I',
                       'Small Capacitor Control Circuit I',
                       'Medium Trimark Armor Pump I',
                       'Small Trimark Armor Pump I',
                       ]
                  },
             'Damian Trias':
                 {'Hadozeko IX - Moon 11 - Boundless Creation Factory':
                      ['10MN Afterburner I',
                       '10MN MicroWarpdrive I',
                       '150mm Light AutoCannon I',
                       '1MN Afterburner I',
                       '1MN MicroWarpdrive I',
                       '200mm AutoCannon I',
                       '425mm AutoCannon I',
                       'Analyzer I',
                       'Antimatter Charge L',
                       'Antimatter Charge M',
                       'Antimatter Charge S',
                       'Atron',
                       'Bane Torpedo',
                       'Berserker I',
                       'Bloodclaw Light Missile',
                       'Breacher',
                       'Cap Booster 200',
                       'Cap Booster 800',
                       'Carbonized Lead M',
                       'Codebreaker I',
                       'Combat Scanner Probe I',
                       'Core Probe Launcher I',
                       'Core Scanner Probe I',
                       'Cynosural Field Generator I',
                       'Depleted Uranium S',
                       'Devastator Cruise Missile',
                       'Dual 180mm AutoCannon I',
                       'EMP L',
                       'EMP M',
                       'Energized Adaptive Nano Membrane I',
                       'Expanded Cargohold I',
                       'Flameburst Light Missile',
                       'Foxfire Rocket',
                       'Fulmination Assault Missile',
                       'Fusion L',
                       'Fusion M',
                       'Fusion S',
                       'Gremlin Rocket',
                       'Gyrostabilizer I',
                       'Hammerhead I',
                       'Havoc Heavy Missile',
                       'Hellfire Assault Missile',
                       'Hurricane',
                       'Inertia Stabilizers I',
                       'Inferno Torpedo',
                       'Invulnerability Field I',
                       'Iridium Charge M',
                       'Iridium Charge S',
                       'Mammoth',
                       'Micro Auxiliary Power Core I',
                       'Minmatar Shuttle',
                       'Mjolnir Torpedo',
                       'Nanofiber Internal Structure I',
                       'Nuclear M',
                       'Overdrive Injector System I',
                       'Paradise Cruise Missile',
                       'Phalanx Rocket',
                       'Phased Plasma L',
                       'Phased Plasma M',
                       'Probe',
                       'Proton M',
                       'Rifter',
                       'Rupture',
                       'Sabretooth Light Missile',
                       'Salvager I',
                       'Scourge Heavy Missile',
                       'Shield Boost Amplifier I',
                       'Slasher',
                       'Stasis Webifier I',
                       'Thorn Rocket',
                       'Thrasher',
                       'Thunderbolt Heavy Missile',
                       'Titanium Sabot M',
                       'Titanium Sabot S',
                       'Torrent Assault Missile',
                       'Tracking Enhancer I',
                       'Valkyrie I',
                       'Warp Core Stabilizer I',
                       'Warp Disruptor I',
                       'Warp Scrambler I',
                       'Warrior I',
                       'Widowmaker Heavy Missile',
                       'Wrath Cruise Missile',
                       ]
                  },
             'Sonja Dragooran':
                 {'Hadozeko IX - Moon 11 - Boundless Creation Factory':
                      ['10MN MicroWarpdrive I',
                       '125mm Gatling AutoCannon I',
                       '125mm Gatling AutoCannon II',
                       '125mm Light Prototype I Automatic Cannon',
                       '150mm Light AutoCannon I',
                       '150mm Light Prototype I Automatic Cannon',
                       '1600mm Reinforced Crystalline Carbonide Plates I',
                       '1600mm Reinforced Steel Plates I',
                       '1MN MicroWarpdrive I',
                       '200mm AutoCannon I',
                       '425mm AutoCannon I',
                       'Analyzer I',
                       'Antimatter Charge L',
                       'Antimatter Charge S',
                       'Atron',
                       'Badger',
                       'Badger Mark II',
                       'Blackbird',
                       'Bloodclaw Light Missile',
                       'Cap Booster 200',
                       'Cap Booster 800',
                       'Carbonized Lead M',
                       'Cataclysm Cruise Missile',
                       'Codebreaker I',
                       'Combat Scanner Probe I',
                       'Core Probe Launcher I',
                       'Core Scanner Probe I',
                       'Cynosural Field Generator I',
                       'Damage Control I',
                       'Damage Control II',
                       'Devastator Cruise Missile',
                       'Drake',
                       'Dual 180mm AutoCannon I',
                       'Dual 180mm Prototype I Automatic Cannon',
                       'ECM - Multispectral Jammer I',
                       'ECM - Phase Inverter I',
                       'ECM - Spatial Destabilizer I',
                       'ECM - White Noise Generator I',
                       'EMP L',
                       'EMP M',
                       'Expanded Probe Launcher I',
                       'Ferox',
                       'Flameburst Light Missile',
                       'Fulmination Assault Missile',
                       'Fusion L',
                       'Fusion M',
                       'Gremlin Rocket',
                       'Griffin',
                       'Gyrostabilizer I',
                       'Gyrostabilizer II',
                       'Hammerhead I',
                       'Hellfire Assault Missile',
                       'Heron',
                       'Hoarder',
                       'Hurricane',
                       'Imicus',
                       'Inferno Torpedo',
                       'Invulnerability Field I',
                       'Iteron Mark III',
                       'Iteron Mark IV',
                       'Iteron Mark V',
                       'Mammoth',
                       'Medium Projectile Ambit Extension I',
                       'Medium Projectile Burst Aerator I',
                       'Medium Shield Extender II',
                       'Micro Auxiliary Power Core I',
                       'Minmatar Shuttle',
                       'Moa',
                       'Mjolnir Torpedo',
                       'Overdrive Injector System I',
                       'Paradise Cruise Missile',
                       'Phased Plasma L',
                       'Phased Plasma M',
                       'Phased Plasma S',
                       'Pneumatic Stabilization Actuator I',
                       'Proton M',
                       'Radioisotope Adaptive Nano Membrane I',
                       'Rifter',
                       'Rocket Launcher I',
                       'Rupture',
                       'Salvager I',
                       'Shield Boost Amplifier I',
                       'Small Anti-EM Screen Reinforcer I',
                       'Small Anti-Thermal Screen Reinforcer I',
                       'Small Projectile Burst Aerator I',
                       'Small Projectile Collision Accelerator I',
                       'Stabber',
                       'Stasis Webifier II',
                       'Thorax',
                       'Thrasher',
                       'Thunderbolt Heavy Missile',
                       'Titanium Sabot L',
                       'Torrent Assault Missile',
                       'Valkyrie I',
                       'Vexor',
                       'Warp Core Stabilizer I',
                       'Warp Disruptor I',
                       'Warp Scrambler I',
                       'Warrior I',
                       'Wrath Cruise Missile'
                       ]
                  },
             'Tercius':
                 {'Egbinger XI - Moon 3 - Republic Fleet Testing Facilities':
                      ["100MN Afterburner I",
                       "100MN Afterburner II",
                       "100MN MicroWarpdrive I",
                       "100MN MicroWarpdrive II",
                       "10MN Afterburner I",
                       "10MN Afterburner II",
                       "10MN MicroWarpdrive I",
                       "10MN MicroWarpdrive II",
                       "1200mm Artillery Cannon I",
                       "1200mm Artillery Cannon II",
                       "125mm Gatling AutoCannon I",
                       "125mm Gatling AutoCannon II",
                       "125mm Railgun II",
                       "1400mm Howitzer Artillery I",
                       "1400mm Howitzer Artillery II",
                       "150mm Light AutoCannon I",
                       "150mm Light AutoCannon II",
                       "150mm Railgun II",
                       "1MN Afterburner I",
                       "1MN Afterburner II",
                       "1MN MicroWarpdrive I",
                       "1MN MicroWarpdrive II",
                       "200mm AutoCannon I",
                       "200mm AutoCannon II",
                       "200mm Railgun II",
                       "220mm Vulcan AutoCannon I",
                       "220mm Vulcan AutoCannon II",
                       "250mm Light Artillery Cannon I",
                       "250mm Light Artillery Cannon II",
                       "250mm Railgun II",
                       "280mm Howitzer Artillery I",
                       "280mm Howitzer Artillery II",
                       "350mm Railgun II",
                       "425mm AutoCannon I",
                       "425mm AutoCannon II",
                       "425mm Railgun II",
                       "650mm Artillery Cannon I",
                       "650mm Artillery Cannon II",
                       "720mm Howitzer Artillery I",
                       "720mm Howitzer Artillery II",
                       "75mm Gatling Rail II",
                       "800mm Repeating Artillery I",
                       "800mm Repeating Artillery II",
                       "Adaptive Nano Plating I",
                       "Adaptive Nano Plating II",
                       "Analyzer I",
                       "Analyzer II",
                       "Armor EM Hardener I",
                       "Armor EM Hardener II",
                       "Armor Explosive Hardener I",
                       "Armor Explosive Hardener II",
                       "Armor Kinetic Hardener I",
                       "Armor Kinetic Hardener II",
                       "Armor Thermic Hardener I",
                       "Armor Thermic Hardener II",
                       "Armored Warfare Link - Damage Control",
                       "Armored Warfare Link - Passive Defense",
                       "Armored Warfare Link - Rapid Repair",
                       "Assault Missile Launcher I",
                       "Assault Missile Launcher II",
                       "Atron",
                       "Badger",
                       "Badger Mark II",
                       "Ballistic Control System I",
                       "Ballistic Control System II",
                       "Ballistic Deflection Field I",
                       "Ballistic Deflection Field II",
                       "Bantam",
                       "Bellicose",
                       "Blackbird",
                       "Breacher",
                       "Brutix",
                       "Burst",
                       "Cap Recharger I",
                       "Cap Recharger II",
                       "Capacitor Flux Coil I",
                       "Capacitor Flux Coil II",
                       "Capacitor Power Relay I",
                       "Capacitor Power Relay II",
                       "Caracal",
                       "Catalyst",
                       "Celestis",
                       "Cheetah",
                       "Co-Processor I",
                       "Co-Processor II",
                       "Codebreaker I",
                       "Codebreaker II",
                       "Command Processor I",
                       "Core Probe Launcher I",
                       "Cormorant",
                       "Covert Cynosural Field Generator I",
                       "Covert Jump Portal Generator I",
                       "Covert Ops Cloaking Device II",
                       "Cruise Missile Launcher I",
                       "Cruise Missile Launcher II",
                       "Cyclone",
                       "Cynosural Field Generator I",
                       "Damage Control I",
                       "Damage Control II",
                       "Dominix",
                       "Drake",
                       "Drone Link Augmentor I",
                       "Drone Navigation Computer I",
                       "Dual 150mm Railgun II",
                       "Dual 180mm AutoCannon I",
                       "Dual 180mm AutoCannon II",
                       "Dual 250mm Railgun II",
                       "Dual 425mm AutoCannon I",
                       "Dual 425mm AutoCannon II",
                       "Dual 650mm Repeating Artillery I",
                       "Dual 650mm Repeating Artillery II",
                       "ECCM - Ladar II",
                       "ECM - Ion Field Projector I",
                       "ECM - Ion Field Projector II",
                       "ECM - Multispectral Jammer I",
                       "ECM - Multispectral Jammer II",
                       "ECM - Phase Inverter I",
                       "ECM - Phase Inverter II",
                       "ECM - Spatial Destabilizer I",
                       "ECM - Spatial Destabilizer II",
                       "ECM - White Noise Generator I",
                       "ECM - White Noise Generator II",
                       "ECM Burst I",
                       "Electron Blaster Cannon II",
                       "Energized Adaptive Nano Membrane I",
                       "Energized Adaptive Nano Membrane II",
                       "Exequror",
                       "Expanded Cargohold I",
                       "Expanded Cargohold II",
                       "Expanded Probe Launcher I",
                       "Explosion Dampening Field I",
                       "Explosion Dampening Field II",
                       "Ferox",
                       "Focused Warp Disruption",
                       "Gas Cloud Harvester I",
                       "Gas Cloud Harvester II",
                       "Gravimetric Backup Array I",
                       "Gravimetric Backup Array II",
                       "Griffin",
                       "Gyrostabilizer I",
                       "Gyrostabilizer II",
                       "Heat Dissipation Field I",
                       "Heat Dissipation Field II",
                       "Heat Sink I",
                       "Heat Sink II",
                       "Heavy Assault Missile Launcher I",
                       "Heavy Assault Missile Launcher II",
                       "Heavy Capacitor Booster I",
                       "Heavy Capacitor Booster II",
                       "Heavy Electron Blaster II",
                       "Heavy Energy Neutralizer I",
                       "Heavy Energy Neutralizer II",
                       "Heavy Ion Blaster II",
                       "Heavy Missile Launcher I",
                       "Heavy Missile Launcher II",
                       "Heavy Neutron Blaster II",
                       "Heavy Nosferatu I",
                       "Heavy Nosferatu II",
                       "Heron",
                       "Hoarder",
                       "Hurricane",
                       "Hyperion",
                       "Ice Harvester I",
                       "Ice Harvester II",
                       "Ice Harvester Upgrade I",
                       "Ice Harvester Upgrade II",
                       "Imicus",
                       "Improved Cloaking Device II",
                       "Incursus",
                       "Inertia Stabilizers I",
                       "Inertia Stabilizers II",
                       "Information Warfare Link - Electronic Superiority",
                       "Information Warfare Link - Recon Operation",
                       "Information Warfare Link - Sensor Integrity",
                       "Interdiction Sphere Launcher I",
                       "Invulnerability Field I",
                       "Invulnerability Field II",
                       "Ion Blaster Cannon II",
                       "Iteron",
                       "Iteron Mark II",
                       "Iteron Mark III",
                       "Iteron Mark IV",
                       "Iteron Mark V",
                       "Kestrel",
                       "LADAR Backup Array I",
                       "LADAR Backup Array II",
                       "Large Armor Repairer I",
                       "Large Armor Repairer II",
                       "Large EMP Smartbomb I",
                       "Large EMP Smartbomb II",
                       "Large Graviton Smartbomb I",
                       "Large Graviton Smartbomb II",
                       "Large Hull Repairer I",
                       "Large Hull Repairer II",
                       "Large Plasma Smartbomb I",
                       "Large Plasma Smartbomb II",
                       "Large Proton Smartbomb I",
                       "Large Proton Smartbomb II",
                       "Large Remote Armor Repair System I",
                       "Large Remote Armor Repair System II",
                       "Large Remote Hull Repair System I",
                       "Large Shield Booster I",
                       "Large Shield Booster II",
                       "Large Shield Extender I",
                       "Large Shield Extender II",
                       "Large Shield Transporter I",
                       "Large Shield Transporter II",
                       "Light Electron Blaster II",
                       "Light Ion Blaster II",
                       "Light Neutron Blaster II",
                       "Maelstrom",
                       "Magnetic Field Stabilizer I",
                       "Magnetic Field Stabilizer II",
                       "Magnetic Plating I",
                       "Magnetic Plating II",
                       "Magnetometric Backup Array I",
                       "Magnetometric Backup Array II",
                       "Mammoth",
                       "Medium Armor Repairer I",
                       "Medium Armor Repairer II",
                       "Medium Energy Neutralizer I",
                       "Medium Energy Neutralizer II",
                       "Medium Energy Transfer Array I",
                       "Medium Energy Transfer Array II",
                       "Medium Hull Repairer I",
                       "Medium Hull Repairer II",
                       "Medium Nosferatu I",
                       "Medium Nosferatu II",
                       "Medium Remote Armor Repair System I",
                       "Medium Remote Armor Repair System II",
                       "Medium Remote Hull Repair System I",
                       "Medium Shield Booster I",
                       "Medium Shield Booster II",
                       "Medium Shield Extender I",
                       "Medium Shield Extender II",
                       "Medium Shield Transporter I",
                       "Medium Shield Transporter II",
                       "Megathron",
                       "Merlin",
                       "Micro Auxiliary Power Core I",
                       "Miner I",
                       "Miner II",
                       "Mining Foreman Link - Harvester Capacitor Efficiency",
                       "Mining Foreman Link - Laser Optimization",
                       "Mining Foreman Link - Mining Laser Field Enhancement",
                       "Mining Laser Upgrade I",
                       "Mining Laser Upgrade II",
                       "Minmatar Shuttle",
                       "Mobile Large Warp Disruptor I",
                       "Mobile Large Warp Disruptor II",
                       "Mobile Medium Warp Disruptor I",
                       "Mobile Medium Warp Disruptor II",
                       "Mobile Small Warp Disruptor I",
                       "Mobile Small Warp Disruptor II",
                       "Modulated Deep Core Miner II",
                       "Modulated Deep Core Strip Miner II",
                       "Modulated Strip Miner II",
                       "Multi Sensor Backup Array I",
                       "Multi Sensor Backup Array II",
                       "Myrmidon",
                       "Nanite Repair Paste",
                       "Nanofiber Internal Structure I",
                       "Nanofiber Internal Structure II",
                       "Navitas",
                       "Neutron Blaster Cannon II",
                       "Noctis",
                       "Omnidirectional Tracking Link I",
                       "Optimal Range",
                       "Optimal Range Disruption",
                       "Osprey",
                       "Overdrive Injector System I",
                       "Overdrive Injector System II",
                       "Photon Scattering Field I",
                       "Photon Scattering Field II",
                       "Power Diagnostic System I",
                       "Power Diagnostic System II",
                       "Probe",
                       "Prototype Cloaking Device I",
                       "RADAR Backup Array I",
                       "RADAR Backup Array II",
                       "Raven",
                       "Reactor Control Unit I",
                       "Reactor Control Unit II",
                       "Remote Sensor Booster I",
                       "Remote Sensor Booster II",
                       "Remote Sensor Dampener I",
                       "Remote Sensor Dampener II",
                       "Rifter",
                       "Rocket Launcher I",
                       "Rocket Launcher II",
                       "Rokh",
                       "Rupture",
                       "Salvager I",
                       "Salvager II",
                       "Scorpion",
                       "Scythe",
                       "Sensor Booster I",
                       "Sensor Booster II",
                       "Shield Boost Amplifier I",
                       "Shield Boost Amplifier II",
                       "Shield Flux Coil I",
                       "Shield Flux Coil II",
                       "Shield Power Relay I",
                       "Shield Power Relay II",
                       "Shield Recharger I",
                       "Shield Recharger II",
                       "Siege Missile Launcher I",
                       "Siege Missile Launcher II",
                       "Siege Warfare Link - Active Shielding",
                       "Siege Warfare Link - Shield Efficiency",
                       "Siege Warfare Link - Shield Harmonizing",
                       "Signal Amplifier I",
                       "Signal Amplifier II",
                       "Signal Distortion Amplifier I",
                       "Signal Distortion Amplifier II",
                       "Skirmish Warfare Link - Evasive Maneuvers",
                       "Skirmish Warfare Link - Interdiction Maneuvers",
                       "Skirmish Warfare Link - Rapid Deployment",
                       "Slasher",
                       "Small Armor Repairer I",
                       "Small Armor Repairer II",
                       "Small Energy Neutralizer I",
                       "Small Energy Neutralizer II",
                       "Small Hull Repairer I",
                       "Small Hull Repairer II",
                       "Small Nosferatu I",
                       "Small Nosferatu II",
                       "Small Remote Armor Repair System I",
                       "Small Remote Armor Repair System II",
                       "Small Remote Hull Repair System I",
                       "Small Shield Booster I",
                       "Small Shield Booster II",
                       "Small Shield Extender I",
                       "Small Shield Extender II",
                       "Small Shield Transporter I",
                       "Small Shield Transporter II",
                       "Stabber",
                       "Standard Missile Launcher I",
                       "Standard Missile Launcher II",
                       "Stasis Webifier I",
                       "Stasis Webifier II",
                       "Survey Scanner I",
                       "Survey Scanner II",
                       "Target Painter I",
                       "Target Painter II",
                       "Tempest",
                       "Thorax",
                       "Thrasher",
                       "Tracking Computer I",
                       "Tracking Computer II",
                       "Tracking Disruptor I",
                       "Tracking Disruptor II",
                       "Tracking Enhancer I",
                       "Tracking Enhancer II",
                       "Tracking Link I",
                       "Tracking Link II",
                       "Tristan",
                       "Typhoon",
                       "Vexor",
                       "Vigil",
                       "Warp Core Stabilizer I",
                       "Warp Core Stabilizer II",
                       "Warp Disruption Field Generator I",
                       "Warp Disruptor I",
                       "Warp Disruptor II",
                       "Warp Scrambler I",
                       "Warp Scrambler II",
                       "Wreathe",
                       "X-Large Shield Booster I",
                       "X-Large Shield Booster II"
                       ]
                  }
             }

conn = None

def main():
    global conn
    conn = db.connect()
    for producer in PRODUCERS:
        locations = {}
        for station in PRODUCERS[producer]:
            types = PRODUCERS[producer][station]
            locations[station] = generate_table(producer, station, types)
        generate_html(producer, locations)

def generate_table(producer, station, types):
    sales = get_sales(producer, station)
    alltypes = list(set(sales.keys() + types))
    alltypes.sort(lambda a, b: cmp(a.lower(), b.lower()))
    result = []
    for typename in alltypes:
        typeid = typename2id(typename)
        if typename in sales:
            (qty, price, number_of_orders, timeleft) = sales[typename]
        else:
            qty = 0
            price = get_last_sell_price(typename, producer, station)
            number_of_orders = 0
            timeleft = datetime.timedelta(days=0)
        production_price = get_production_price(typename)
        avg7dvol = get_daily_volume(typename, producer, station, 7)
        avg28dvol = get_daily_volume(typename, producer, station, 28)
        if avg28dvol == 0:
            trend = 0.0
        else:
            trend = avg7dvol / float(avg28dvol)
        if price == 0:
            profit = 1
        else:
            profit = (1 - (production_price / price))
        row = Row(typeid=typeid, typename=typename,
                  qty=qty, number_of_orders=number_of_orders,
                  sell_price=price, production_price=production_price,
                  trend=trend,
                  volumeprofit=avg28dvol * (price - production_price),
                  profit=profit,
                  timeleft=timeleft)
        result.append(row)
    return result

class Row(object):
    def __init__(self, **kwargs):
        self._kw = kwargs
        for k, v in kwargs.items():
            setattr(self, k, v)

    def __repr__(self):
        return "<%s %s>" % (self.__class__.__name__,
                            ", ".join(["%s=%r" % (k, v)
                                       for (k, v) in self._kw.items()]))

def get_sales(producer, station):
    """
    Return a mapping of typename to sell order.
    A sell order consists of a triple of total quantity, minimum
    price, and number of orders for this type.
    """
    corp = api.corp()
    cmo = corp.MarketOrders()
    result = {}
    charid = charactername2id(producer)
    staid = stationname2id(station)
    storedvolume = {}
    for order in cmo.orders:
        if order.orderState != 0 or order.bid == 1:
            continue
        if order.charID != charid or order.stationID != staid:
            continue
        typename = typeid2name(order.typeID)
        result.setdefault(typename, (0, None, 0, None))
        (qty, price, number_of_orders, timeleft) = result[typename]
        qty += order.volRemaining
        if price is None:
            price = order.price
            storedvolume[typename] = order.volRemaining
        else:
            lastvolume = storedvolume[typename]
            if order.volRemaining > lastvolume:
                price = order.price
                storedvolume[typename] = order.volRemaining
        number_of_orders += 1
        newtimeleft = ((datetime.datetime.utcfromtimestamp(order.issued) +
                        datetime.timedelta(days=1) * order.duration) -
                       datetime.datetime.utcnow())
        if timeleft is None:
            timeleft = newtimeleft
        else:
            timeleft = min(timeleft, newtimeleft)
        result[typename] = (qty, price, number_of_orders, timeleft)
    return result

_production = None
def get_production_price(typename):
    global _production
    if _production is None:
        r = csv.reader(file("/home/forcer/public_html/eve/grd-pricelist.txt"))
        _production = dict((row[0], float(row[1])) for row in r)
    return _production.get(typename, 0.0)

def get_daily_volume(typename, producer, station, days):
    """
    Average daily volume sold of typename in the last n days
    """
    c = conn.cursor()
    c.execute("SELECT SUM(quantity) "
              "FROM grd_transactions "
              "WHERE transactiontype = 'sell' "
              "  AND typename = %s "
              "  AND charactername = %s "
              "  AND stationname = %s "
              "  AND date > NOW() - INTERVAL '%s days'",
              (typename, producer, station, days))
    qty = c.fetchone()[0]
    if qty is None:
        return 0
    else:
        return qty / float(days)

def get_last_sell_price(typename, producer, station):
    c = conn.cursor()
    c.execute("SELECT price "
              "FROM grd_transactions "
              "WHERE transactiontype = 'sell' "
              "  AND typename = %s "
              "  AND charactername = %s "
              "  AND stationname = %s "
              "ORDER BY date DESC LIMIT 1",
              (typename, producer, station))
    if c.rowcount == 0:
        return 0.0
    else:
        return c.fetchone()[0]

_typename2id = None
_typeid2name = None
def maketypecache():
    global _typename2id
    global _typeid2name
    if _typename2id is None:
        c = conn.cursor()
        c.execute("SELECT typeid, typename FROM invtypes")
        _typename2id = {}
        _typeid2name = {}
        for row in c.fetchall():
            _typename2id[row.typename] = row.typeid
            _typeid2name[row.typeid] = row.typename

def typename2id(typename):
    maketypecache()
    return _typename2id[typename]

def typeid2name(typeid):
    maketypecache()
    return _typeid2name[typeid]

def charactername2id(charname):
    eve = api.api().eve
    chars = eve.CharacterID(names=charname)
    return chars.characters[0].characterID

_stations = None
def stationname2id(staname):
    global _stations
    if _stations is None:
        c = conn.cursor()
        c.execute("SELECT stationname, stationid FROM ccp.stastations")
        _stations = dict(c.fetchall())
    return _stations[staname]

def htmlquote(s):
    return s.replace("&", "&amp;").replace("<", "&lt;")

def typelink(typeid, typename):
    return '<span style="color: blue; text-decoration: underline; cursor: pointer" onClick="CCPEVE.showMarketDetails(%s)">%s</span>' % (typeid, typename)

def generate_html(producer, locations):
    # outfile = ("/home/forcer/public_html/eve/producer/%s.html" %
    #            producer.replace(" ", "_"))
    # w = file(outfile, "w")
    w = StringIO.StringIO()
    w.write('<html><head><style type="text/css">')
    w.write("html {\n"
            "  font-family: sans-serif;\n"
            "}\n"
            "table {\n"
            "  border-collapse: collapse;\n"
            "}\n"
            "td, th {\n"
            "  border: 1px solid #7F7F7F;\n"
            "  padding: 0.1em 0.3em;\n"
            "}\n"
            'th {\n'
            '  background: #CFCFCF;\n'
            '}\n'
            'tr.even td {\n'
            '  background: #EFEFEF;\n'
            '}\n'
            'td.numeric {\n'
            '  text-align: right;\n'
            '}\n'
            )
    w.write("</style>\n")
    w.write('<script type="text/javascript" src="/js/jquery.js"></script>\n'
            '<script type="text/javascript" src="/js/jquery.tablesorter.js"></script>\n')
    w.write('<script type="text/javascript">')
    w.write("""
$(function () {
    $("#thetable").tablesorter({
        widgets: ['zebra'],
        headers: {
            0: { sorter: 'text' },
            1: { sorter: 'test' },
            2: { sorter: 'digit' },
            3: { sorter: false },
            4: { sorter: false },
            5: { sorter: 'percent' },
            5: { sorter: 'percent' },
            6: { sorter: 'digit' },
        },
    });
});
""")
    w.write('</script>')
    w.write("</head>")
    w.write("<body>\n<h1>%s</h1>\n" % htmlquote(producer))
    locnames = locations.keys()
    locnames.sort()
    for loc in locnames:
        w.write("<h2>%s</h2>\n" % htmlquote(loc))
        w.write('<table id="thetable">\n'
                "<thead>"
                "<tr>"
                "<th>Typename</th><th>State</th><th>Quantity</th>"
                "<th>Sell Price</th>"
                "<th>Production Price</th><th>Profit Margin</th>"
                "<th>Trend</th><th>Volume Profit</th>"
                "<th>Time Left</th>"
                "</tr>"
                "</thead><tbody>\n")
        n = 1
        for row in locations[loc]:
            n += 1
            state = ""
            if row.number_of_orders < 1:
                state = "<b>Out</b>"
            if row.number_of_orders > 1:
                state = "Duplicated (x%i)" % row.number_of_orders
            if row.sell_price < row.production_price:
                sell_price = ('<span style="color: #FF0000;">%s</span>'
                              % humane(row.sell_price))
            elif row.sell_price < row.production_price * 1.1:
                sell_price = ('<span style="color: #FF7F00;">%s</span>'
                              % humane(row.sell_price))
            else:
                sell_price = humane(row.sell_price)
            w.write('<tr>'
                    '<td>%s</td>'
                    '<td>%s</td>'
                    '<td class="numeric">%i</td>'
                    '<td class="numeric">%s</td>'
                    '<td class="numeric">%s</td>'
                    '<td class="numeric">%.2f%%</td>'
                    '<td class="numeric">%.2f%%</td>'
                    '<td class="numeric">%.2f</td>'
                    '<td class="numeric">%.2f</td>'
                    "</tr>" %
                    (typelink(row.typeid, htmlquote(row.typename)), state,
                     row.qty,
                     sell_price, humane(row.production_price),
                     row.profit*100,
                     row.trend*100, row.volumeprofit,
                     row.timeleft.days + (row.timeleft.seconds /
                                          (24*60*60.0))))
        w.write("</tbody></table>")
    w.seek(0)
    ftp.upload("%s.html" % producer.replace(" ", "_"),
               w,
               "secure",
               "sales")

if __name__ == '__main__':
    main()
